name: sample_downloader
description: An command line tool for downloading Flutter projects from GitHub.
version: 0.1.0
repository: https://github.com/filiph/sample_downloader

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  archive: ^3.4.9
  args: ^2.4.2
  cli_menu: ^0.4.0
  cli_util: ^0.4.0
  github: ^9.20.0
  http: ^1.1.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

executables:
  sample_downloader:
